name : java maven with actions

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking code
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: install dependencies
        run: mvn dependency:resolve

      - name: build and test
        run: mvn clean install

      - name: run tests
        run: mvn test

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-artifact
          path: target/*.jar

